### ISSUE TITLE
share link

### ISSUE THREAD

**Issue by ilood** [broncowdd/BoZoN#102]
Bonjour,

J'ai partagé un dossier à l'autre utilisateur, mais quand j'ai voulu arrêter ce partage en utilisant "regen the share link", le lien de partage reste toujours dans cet utilisateur. Comment faire pour mettre ces liens ne plus valables disparaît dans l'espace de l'utilisateur, soit c'est un bug ?  Merci par avance.

Bien cordialement,
Ilood

**Comment by eauland** [comment]
Bonjour,

C'est un problème que j'ai déjà remarqué, pour l'instant il faut éditer le fichier folder_share.php dans private à la main, ou l'effacer et recommencer les partages de dossiers désirés.

**Comment by broncowdd** [comment]
En effet, c'est une chose à corriger, merci :-)

**Comment by broncowdd** [comment]
problème résolu pour la prochaine version 2.4 ;-)

**Comment by eauland** [comment]
Un truc que je ne comprendrais jamais c'est pourquoi attendre une version pour résoudre les problèmes... pas très logique vu le nombre de bugs... enfin bref, j'ai pas la même logique.

**Comment by broncowdd** [comment]
Je sais, mais le souci, c'est que je bosse tout le temps dessus et que quand on me remonte un bug, je le corrige mais sur la version en cours (car autant adapter la correction sur la version la plus optimisée). 
Du coup, j'attends que la version soit stable...

**Comment by broncowdd** [comment]
Après, si tu veux poster des correctifs temporaires, pas de problème: pour ma part, je n'ai pas le temps de corriger des trucs sur plusieurs versions en même temps.

**Comment by eauland** [comment]
Je voyais plus une idée de poster des zip de dist et de poster constamment le reste sur github qui est pour le dev, c'est seulement comme ça qu'on aurait pu bosser sur le même code.

**Comment by eauland** [comment]
Sinon github ça sert à rien autant donner un zip sur son site ça revient au même....

**Comment by broncowdd** [comment]
j'imagine: toutefois, je corrige et modifie le tout au fur et à mesure des remontées et des demandes... je n'ai même pas le temps de tester complètement. Par exemple, j'ai modifié profondément la génération de l'arborescence pour l'optimiser au maximum (pour les gens ayant un très grand nombre de fichiers)
A elle seule, cette modif vient de me prendre une dizaine de jours: améliorer, débuguer, modifier etc... 
Et tant que ça ne fonctionnait pas, impossible de passer le code, tu en conviendras.
Comme cette modif provoquait des incompatibilités avec le reste des demandes, il me fallait adapter le tout à la nouvelle version au fur et à mesure.
Et heureusement que Cyrille teste vachement toutes les versions: on a fait une vingtaine de versions alphas et on en est aux bétas.
Tout ça sur notre temps libre ^^ \o/

**Comment by broncowdd** [comment]
C'est ton point de vue...

**Comment by eauland** [comment]
Juste que mes modifs j'ai pas envie de me prendre la tête à les refaire tous les 2/4/6 si elles sont pas intégrées exactement comme je l'ai fait... sachant que du bosse en caché, il est impossible de savoir où tu en es et s'adapter, bref c'est impossible de collaborer, d'où mon fork, avec mes idées, parfois bonne, des fois moins, mais comme je pense que c'est pas voué à une autre utilisation que personnelle ou familial ça passe.

Mais là tu dis que cyrille fait des teste sur du code à un instant T je n'ose pas dire alpha pour des raison propres, les autres ne peuvent pas le faire car ils n'ont pas le code, donc ma logique est irréprochable.

CQFD.

**Comment by broncowdd** [comment]
Mais oui, t'as raison, rassure-toi... ça à l'air tellement important pour toi...
Tu redeviens agressif et ça commence à m'agacer: pense ce que tu veux mais ne viens pas m'expliquer ta façon de voir les choses... 
Moi, j'y passe tout mon temps libre POUR LES AUTRES, car je n'ai pas l'utilité d'une telle appli. Je le fais par passion, par altruisme aussi, mais je n'ai PAS LE TEMPS de faire des commits toutes les minutes. 
Et même si je le faisais, je reste persuadé que tu trouverais encore à redire (qu'on arrive pas à suivre, que cette modif pose problème pour toi, qu'il va ENCORE falloir que tu refasses tout... je l'entends d'ici)

"tu bosses en caché"... "impossible de collaborer" 
Tout ça, ce n'est qu'une opinion... pas une démonstration.

Si c'est vraiment ce que tu penses, sois cohérent: travaille sur ton fork, fais tes commits à ton rythme, râle dans ton coin, corrige les bugs...  mais arrête de me donner des leçons parce que ça commence à bien faire.

**Comment by eauland** [comment]
C'est pas agressif, faut pas prendre ça comme ça, j'ai refait lire mes comm personne m'a dit que c'était agressif sauf toi.

En mettant tjs le github à jours d'autres pourrait aider, dc plus de temps libre pour toi après tu fais comme tu veux, j'ai réglé le problème en forkant ça, donc je m'en fiche un peu de comment tu fais, je te dis juste que c'est complétement illogique, heureusement que ya des CAPES de maths dans l'air car pour moi c'est une aberration.

Après comme je te dis tout les bon projets fonctionne avec des nightly donc faut pas me sortir l'inverse, bossé en caché = impossible de collaborer c'est de la pure logique et pas une opinion.

Je suis très objectif et ferme c'est tout. Mais comme je dis faut rien prendre mal car bon je fais mon petit chemin sur une version perso où je bosse pour mes besoins et mes envies sans y passer tout mon temps libre ;).

**Comment by broncowdd** [comment]
sois objectif et ferme... mais dans ton coin.

**Comment by eauland** [comment]
Si c'est dans son coin c'est subjectif...

**Comment by broncowdd** [comment]
Parce que confonds objectivité et obstination, c'est tout.
La subjectivité ou l'objectivité ne dépendent en rien du nombre de personnes qui sont en contact avec elle. 
Pour ma part, je n'ai aucune envie d'avoir régulièrement quelqu'un qui vient me faire la morale ou m'expliquer que c'est pas comme ça qu'on fait. Je suis patient depuis le début, mais même ma patience s'épuise.
Donc, je le répète: fais ce que tu veux, pense ce que tu veux, mais ne viens pas m'en faire part, ça ne m'intéresse pas et ça m'indispose. Merci.

**Comment by eauland** [comment]
Je confond pas, si je garde mes critiques pour moi il n' y a aucun intérêt à être objectif, on est subjectif.

Je suis loin d'être obstiné/têtu, il y a des logiques qui permettent à certains d'avoir des correctifs, et quand on fait de l'opensource bah on ouvre son code à chaque moment. Certes ça reste libre mais c'est pas pratique ni pour les utilisateurs, ni pour les développeurs et encore moins pour toi.

J'ai plutôt l'impression que c'est toi qui est têtu à t'enfermer dans une logique qui mène à rien.

Tu mélanges un peu tout pour essayer de retourner ça à ta sauce.

Bref, je continu sur mes modifs, ça sert à rien d'essayer de s'accorder, on a ni la même logique ni la même envie, et même si on me disait que je codais comme une bille, je ne cherche pas à me prouver quelque chose en me donnant à 100% sur quelque chose qui me parait accessoire.

**Comment by kameka22** [comment]
Salut ^^
Désolé de m'immiscer dans votre conversation mais eauland à raison. Dommage de s'éparpiller sur plusieurs projets quand le but reste à peut prêt le même...
Broncowdd, je voie que tu n'a créé aucune autre branche que la master, alors que tes modifs tu pourrais les balancer à la volée dans une autre branche ce qui permettrait a d'autres de tester et te libérer du temps...

**Comment by broncowdd** [comment]
en effet, comme je l'ai mentionné à plusieurs reprises, je ne disconviens pas du fond... c'est la forme qui m'agace et même si ça peut paraître peu dans cette conversation, il y a toujours une goutte qui fait déborder un vase. 
Ma maîtrise de github n'est que très fragmentaire, pour le moins, et j'admets très volontiers qu'un habitué se servirait de cet outil comme il convient (d'ailleurs, Eauland m'a, à plusieurs reprises, taxé d'amateurisme, ce que j'ai accepté sans broncher et en demandant plus d'infos pour m'améliorer)
J'accepte toujours les critiques car elles permettent d'avancer (et on ne met pas son code en ligne si l'on n'est pas prêt à les accepter) mais qu'on se croie le droit de les faire sur n'importe quel ton, non.
Le fait de dire la vérité n'exonère pas de diplomatie et de courtoisie.

**Comment by broncowdd** [comment]
Dommage, je viens de m'apercevoir que mon dernier commentaire en réponse à Eauland n'a pas été posté... 
En gros, Eauland, je disais qu'en effet, on ne pouvait taxer d'obstination quelqu'un qui s'entêtait à poursuivre une conversation comme celle-là sans jamais reconnaître qu'il est blessant...
Et c'est incontestable que jusque là j'ai fait preuve d'un esprit obtus et réfractaire au changement et aux critiques si aimablement formulées (j'invite tout un chacun à suivre certaines discussions pour s'en convaincre): je n'ai en effet pas du tout pris les attaques avec humour et jamais je n'ai intégré les modifications proposées en étant content de pouvoir m'améliorer... Encore une fois, il suffit de suivre l'historique de ce dépôt pour voir qui est désagréable et obstiné ici.

Donc, j'ai déjà tapé du poing sur la table une fois et je commence à en avoir marre de devoir montrer les dents pour que tu me témoigne un minimum de considération quand tu t'adresses à moi.

On peut me critiquer sans problème et ça ne m'a jamais rien coûté de reconnaître mes erreurs mais je n'ai pas à accepter que n'importe qui s'adresse à moi comme bon lui semble. Je ne l'accepte pas des gens que j'ai en face de moi, il n'y a aucune raison que je le fasse avec mes interlocuteurs numériques.

Donc, je rétière mon invitation: Eauland, tu peux penser ce que tu veux de ce que je fais ou de moi, comme c'est ton droit le plus absolu, mais tu gardes tes considérations pour toi. 
Si tu t'adresses à moi pour me proposer une critique légitime et constructive, tu me montres le même respect et la même courtoisie que celle que je t'ai toujours témoignée ou tu ne t'adresse pas à moi. 
Point.

**Comment by ilood** [comment]
Bonjour à tous,

Merci pour vos commentaires et vos aides ^ ^ .  Le projet BoZon est super bien, merci à Broncowdd et à ce qui ont constribué à ce projet. 

A propos, j'ai essayé la nouvelle version 2.4beta, qui est vraiment bien d'avoir les nouveaux fonctionalité, mais il semble qu'il y a encore des bugs, comme l'affichage de l'image, le share link, etc.

Bien cordialement,
Zhiqiang

**Comment by broncowdd** [comment]
N'hésite pas à remonter les bugs afin que je corrige au fur et à mesure (comme je n'ai pas de fonctionnalités à ajouter dans l'immédiat, je pourrai les répercuter directement sur ce dépôt)
Dans quelles conditions as-tu des erreurs ?

**Comment by ilood** [comment]
Bonsoir,

Je vois que l'affichage de l'image est corrigé. Pour le share-link, on peut annuler le partage en décochant la case de l'utilisateur, mais à condition qu'il y ait au moins 3 utilisateurs dans BoZoN, par example, s'il n'y a que deux utilisateurs, on peut partager le dossier entre eux, mais on n'arrive pas annuler le partage en décochant la case ou regen le share link.  Même si on a trois utilisateurs, si on partage le dossier pour les autres deux utilisateurs, on ne peut pas annuler ce partage pour les deux ensemble, soit annuler pour l'un ou soit pour l'autre.

**Comment by broncowdd** [comment]
Ok, je viens de corriger... Je fais un commit ce soir. Merci

Le 22 mars 2016 00:19:22 CET, ilood <notifications@github.com> a écrit :
>Bonsoir,
>
>Je vois que l'affichage de l'image est corrigé. Pour le share-link, on
>peut annuler le partage en décochant la case de l'utilisateur, mais à
>condition qu'il y ait au moins 3 utilisateurs dans BoZoN, par example,
>s'il n'y a que deux utilisateurs, on peut partager le dossier entre
>eux, mais on n'arrive pas annuler le partage en décochant la case ou
>regen le share link.  Même si on a trois utilisateurs, si on partage le
>dossier pour les autres deux utilisateurs, on ne peut pas annuler ce
>partage pour les deux ensemble, soit annuler pour l'un ou soit pour
>l'autre.
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/102#issuecomment-199531647

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by ilood** [comment]
Super, ça fonctionne bien maintenant. A propos, je vois qu'il y a une partie de codes dans header.php ne fonctionne plus:

  <?php
    }

    if (!is_user_connected()||!empty($_GET['f'])){ ?>
      <p id="logo" href="index.php">BoZoN</p>
      <h2 class="slogan"><?php e('Drag, drop, share.');?></h2>
  <?php
    }else{
      if (is_allowed('upload')){include('core/auto_dropzone.php');}
    }
  ?>

 Est-ce que l'on peut le remettre ? ^^ merci.

**Comment by broncowdd** [comment]
Je regarde ce soir ;-)

**Comment by ilood** [comment]
Merci, en fait j'ai trouvé qu'il faut juste corriger le code ci-dessous: 
 <p id="logo" href="index.php">BoZoN</p>

par 
 <a id="logo" href="index.php">BoZoN</a>

**Comment by ilood** [comment]
Bonsoir,

J'ai l'autre question à demander, est-ce que la fonction de télécharger en zip peut être réalisé sans demande d'ajouter "Options Indexes" dans la config de apache2 ? Car ça va poser le problème de sécurité. Merci.

**Comment by ilood** [comment]
Je vois l'autre bug: Quand on clique le nom de fichier, il télécharge le fichier avec ce nom de fichier, mais si on clique l'autre fichier, il télécharge le fichier sans ce nom de fichier, mais toujours avec le nom de fichier précédent.

**Comment by eauland** [comment]
Il y a deux solutions, soit créer un zip dans le dossier de l'utilisateur, soit avec un dossier temporaire.
J'ai déjà soulever le problème il y a plus d'un mois...

Pour l'instant j'ai fait un truc à l'arrache

  // zipper et télécharger un dossier
  if(!empty($_GET['zipfolder'])){
    $folder=id2file($_GET['zipfolder']);
    if (!is_dir('temp'))
      mkdir('temp');
    if(!is_dir('temp/'.$_SESSION['login']))
      mkdir('temp/'.$_SESSION['login']);
    if(!is_dir('temp/'.$_SESSION['login'].'/'.$token))
      mkdir('temp/'.$_SESSION['login'].'/'.$token);
    $zipfile='temp/'.$_SESSION['login'].'/'.$token.'/'.basename($folder).'-'.$_GET['zipfolder'].'.zip';
    if(file_exists($zipfile)) unlink($zipfile);
    zip($folder,$zipfile);
    header('location: '.$zipfile);
    exit;
  }

**Comment by ilood** [comment]
Bonjour,

J'ai pas essayé la première méthode, car c'est pas très pratique pour les utilisateurs. Pour la deuxième méthode, j'ai essayé ta fonction, mais ça ne marche pas, peut-etre c'est à cause de la version que j'utilise, (2.4, build3) .

Pour  donner le plus de l'information sur cette issue, j'ai copié le message que j'ai rencontré:
Forbidden

You don't have permission to access /BoZoN/private/temp/demo-TEST.zip on this server.

Voilà, je n'ai pas voulu changer la config du serveur Apache pour donner la permission, donc dans le code PHP, est-ce que l'on contourne cette permission ?

**Comment by ilood** [comment]
J'ai aussi une demande: est-ce que c'est faisable si le root du serveur copie directement les fichiers dans le upload de l'utilisateur pour que les fichiers soit apparus dans l'espace de l'utilisateur sans demander à l'utilisateur de les télécharger dans leur espace. Je vois qu'il y a les advantages pour les gros fichiers et le nombre fichiers, et plus pratique si les fichiers sont dans les serveurs, etc.

**Comment by eauland** [comment]
Normal le dossier zippé reste dans private, bon chez moi ça marche mais vu toutes mes modifications il est difficile de dire que j'utilise tel ou tel version de bozon, vu que je pars dans mes idées.

Je regarde ça et je te file une fonction qui marche dans pas longtemps.

**Comment by eauland** [comment]
Pour ton 2ee commentaire j'ai pas tout compris.

**Comment by eauland** [comment]
Les joies de coder avec bronco, où ya du code partout et où la logique est désirable...

Bref là c'est dans command_get_var à la ligne 77

if(!empty($_GET['zipfolder']) && $_SESSION['zip']){
$folder=id2file($_GET['zipfolder']);
$token=$_GET['token'];
if(!is_dir('temp'))
mkdir('temp');
if(!is_dir('temp/'.$_SESSION['login']))
mkdir('temp/'.$_SESSION['login']);
if(!is_dir('temp/'.$_SESSION['login'].'/'.$token))
mkdir('temp/'.$_SESSION['login'].'/'.$token);
$zipfile='temp/'.$_SESSION['login'].'/'.$token.'/'.basename($folder).'-'.$_GET['zipfolder'].'.zip';
if(file_exists($zipfile)) unlink($zipfile);
zip($folder,$zipfile);
header('location: '.$zipfile);
exit;
}

Par contre tu risques d'avoir des problèmes avec le zip sur un dossier partagé, enfin moi je ne permettrais jamais ça, il ne faut pas tjs écouter les utilisateurs, bcp ne savent pas où ils veulent aller.

Bref je suis pas mécontent d'avoir forker le truc, une vrai usine à gaz avec une logique changeante, des idées farfelues et j'en passe.
Je suis pas un pro très loin de là mais l'ergonomie est repartie dans une logique qu'il faudrait m'apprendre....

**Comment by broncowdd** [comment]
www.eauland.com => 

Fatal error: Uncaught Error: Function name must be a string in /home/graffitiyi/eauland.com/www/core/lib/class.plx.plugins.php:87 Stack trace: #0 /home/graffitiyi/eauland.com/www/core/lib/class.plx.motor.php(105): plxPlugins->callHook('plxMotorConstru...') #1 /home/graffitiyi/eauland.com/www/core/lib/class.plx.motor.php(54): plxMotor->__construct('./data/configur...') #2 /home/graffitiyi/eauland.com/www/index.php(62): plxMotor::getInstance() #3 {main} thrown in /home/graffitiyi/eauland.com/www/core/lib/class.plx.plugins.php on line 87

Quel professionnalisme ! La logique Eulandienne à son apogée...
ça met en perspective toutes les remarques désobligeantes ^^

Un bel exemple d'amateurisme.

**Comment by eauland** [comment]
Merci pour ton retours mais il s'agit d'un problème de pluxml avec php 7.0, bien essayé ;)

**Comment by broncowdd** [comment]
«Tu as perdu une occasion de te taire»... Venant de toi, c'est assez gonflé.
Que le problème vienne de php 7 ou pas ça la fout mal.
Pour le reste, j'utilise ce que je veux... C'est assez curieux que tu continues à donner ton avis alors que je te répète que je m'en torche.
Au passage, l'utilisation de glob limite les versions de php utilisables. C'est nul.

Tant qu'on y est, si tu pouvais faire un effort en ce qui concerne la maîtrise de la langue et l'orthographe, ça m'arrangerait: tu te dis un cador en matière de langage de programmation mais il semble que ta propre langue maternelle te pose quelques difficultés :-)

En tout cas, ça pique.
Je comprends que tu sois «Septique» au vu de tes propos souvent nauséabonds... C'est un aveu ou simplement de l'incompétence ?!
(remarque, le cumul ne t'est pas interdit...)
bon, en attendant, je virerai tous tes messages à partir du moment où tu tiendras des propos désagréables, comme on le fait avec n'importe quel gêneur...

**Comment by eauland** [comment]
Sur mon mutu j'ai pas qu'un site chouchou, et il est impossible de choisir une version de php pour chaque domaine sur l’hébergement, et comme je fais des tests... et oui je m'en tape d'easyphp, je fais tout sur le serveur. Ça pique pour toi, un blog pour lequel je poste rarement je m'en fiche un peu mais pourtant je sais où il y a des bugs mais c'est pas ma priorité.

Je me suis jamais dit cador en php ou autre c'est toi qui insinue ça pour discréditer les remarques des autres, par contre oui je suis très logique, et il me semble avoir déjà dis que mon ortho était douteuse donc tu parles dans le vent, tu dis de la merde pour avoir un semblant de fierté. Maintenant vu la jeunesse je suis pas à plaindre avec mon ortho. CAPES de la démagogie Bronco ?

Pour finir un incompétent qui t'a recodé un thème que tu as détruit en 2 versions bêtement, champion garçon !!

Tu es orgueilleux mais tu le ne remarques même pas, c'est beau de regarder son nombril.

**Comment by cborne** [comment]
Je vais quand même me permettre un simple commentaire. Stéphane Ferrari
développeur de Pluxml et Jerry ont apporté correction et contribution,
ils ne se sont permis aucun jugement désagréable et se sont contentés
d'apporter leur aide simplement. 

Tu peux avoir raison sur le fond, il y a quand même dans cette démarche
systématique de dénigrement quelque chose de malsain. Tu as pourtant
deux options qui sont simples :

- tu contribues au projet en arrêtant de traiter les gens d'incapable et
d'être désagréable même si tu peux avoir raison en présentant simplement
ce qui ne va pas, ce qui ne te paraît pas logique ou cohérent.

- tu as fait ton fork, tu as les compétences pour mener un projet
parallèle et faire ce qui te parait juste ou bien. 

Revenir ici de façon systématique, à vouloir poursuivre une conversation
ça donne un côté de gars qui a vraiment que ça à faire de ses journées. 

Je te souhaite un agréable week-end et t'invite à prendre l'une des deux
décisions qui sera bonne pour tout le monde. Et si tu dois partir et que
le code de BoZon c'est de la merde, il faudra peut être plus de temps
pour trouver les erreurs que tu as déjà vues, et bien tant pis, parfois
mieux vaut être seul que mal accompagné, nous avons la chance sur ce
projet d'avoir pas mal de gens compétents sur ce projet, avec un peu de
chance on en aura d'autres.

**Comment by eauland** [comment]
Non cyrille je viens ici pour récupérer des rapports de bugs, et je met mon code publique pour respecter l'AGPL c'est tout. Sinon c'est juste un truc personnel pas du tout optimiser, mais qui convient à mes besoins.

**Comment by cborne** [comment]
La remarque pour le code public a bien été entendue, Bronco qui a tout
de même une vie de famille bien remplie, un métier, n'a pas pu pousser
dans github à chaque bug que je remontais. Je ne justifie pas,
j'explique simplement. 

Les choses vont désormais se stabiliser avec la version 2.4 qui vient de
paraître, nous montons un site en parallèle. Si certes amateurisme il y
a, il ne faut pas cracher sur le travail accompli, sur l'ambiance, et je
trouve que si ta démarche est peut être justifiée d'un point de vue
technique, elle est vide de tout sens humain. 

Nous ne sommes pas des robots, juste des gars qui faisont un programme
dans la bonne ambiance, tu pourrais choisir de faire les choses
différemment tu préfères l'agressivité. Je trouve ça dommage, ça n'aide
personne sauf à braquer les individus qui n'écouteront plus les
remarques aussi intelligentes soient elles. 

Tu as la pleine liberté de changer ton attitude ou d'éviter les
commentaires et te contenter de récupérer les rapports de bugs. 

Je rajouterai à ça puisque tu as remis sur le tapis plus d'une fois que
nous étions profs, et effectivement du fait d'être profs, nous avons
quand même une patience assez démesurée et ce qui est formidable avec
nous c'est qu'on n'a pas besoin de demander pardon, on se contente
uniquement des changements d'attitudes. 

Pour être respectueux, il faut être respectable, notre métier nous
apprend aussi à valoriser pas uniquement la performance mais aussi ceux
qui essaient de bon coeur. Si pour avoir le meilleur code il faut
traiter les gens comme de la merde, et bien on se passera du meilleur
code. 

Je te demande donc de respecter cette demande, si tu penses que tu n'es
pas capable d'écrire les choses autrement qu'en rentrant dans le tas ce
qui est faux car tu as des interventions qui sont souvent correctes,
alors n'intervient pas, ça évitera à tout le monde de se chercher
querelle. 

Bonne soirée.

**Comment by broncowdd** [comment]
Ben voilà, tout est dit.
